global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'linkerd'
  metrics_path: /admin/metrics/prometheus

  static_configs:
  - targets:
    - '10.0.3.100:4142'
    - '10.0.3.101:4142'
    - '10.0.3.102:4142'
    - '10.0.7.163:4142'

  relabel_configs:
  # strip off port
  - source_labels: [__address__]
    action: replace
    target_label: instance
    regex: (.+)(?::\d+)
    replacement: $1

  metric_relabel_configs:
  # remove explicit linkerd proxy ports
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:([^:]+):srv:0_0_0_0:[^:]+:(.*)
    replacement:   rt:$1:srv:0_0_0_0:port:$2
  # write service names into label {service:"app1"}
  - source_labels: [__name__]
    action:        replace
    target_label:  service
    regex:         rt:[^:]+:dst:id:_:io_l5d_marathon:([^:]+):.*
    replacement:   $1
  # write service name into label (for linkerd)
  # rt:stats:dst:id:_:inet:127_1:9990:requests =>
  # rt:stats:dst:id:_:inet:127_1:9990:requests{service:"linkerd"}
  - source_labels: [__name__]
    action:        replace
    target_label:  service
    regex:         rt:[^:]+:dst:id:_:inet:127_1:9990:.*
    replacement:   linkerd
  # remove service name from metric (linkerd:incoming:requests)
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:([^:]+):dst:id:_:io_l5d_marathon:[^:]+:(.*)
    replacement:   linkerd:$1:$2
  # remove service name from metric for linkerd (linkerd:incoming:requests)
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:([^:]+):dst:id:_:inet:127_1:9990:(.*)
    replacement:   linkerd:$1:$2
  # now merge all linkerd:*:* stats into linkerd:incoming:*
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    # regex:         linkerd:[^:]+:(.*)
    regex:         linkerd:(incoming|stats):(.*)
    replacement:   linkerd:incoming:$2
